pub fn lookup_pnp_manufacturer(id: &str) -> Option<&'static str> {
    match id.trim().to_ascii_uppercase().as_str() {
        "AOC" => Some("AOC International"),
        "AUS" => Some("ASUSTek Computer"),
        "ACR" => Some("Acer"),
        "ACI" => Some("Asus"),
        "BNQ" => Some("BenQ"),
        "CMN" => Some("Chi Mei"),
        "CMO" => Some("Chi Mei Optoelectronics"),
        "DEL" => Some("Dell"),
        "EIZ" => Some("EIZO"),
        "FUS" => Some("Fujitsu"),
        "GSM" => Some("LG Electronics"),
        "HPN" | "HWP" => Some("HP"),
        "LEN" => Some("Lenovo"),
        "LGD" | "LPL" | "LGP" => Some("LG Display"),
        "MSI" => Some("Micro-Star International"),
        "NEC" => Some("NEC"),
        "PHL" => Some("Philips"),
        "SAM" | "SEC" => Some("Samsung"),
        "SHP" => Some("Sharp"),
        "SNY" => Some("Sony"),
        "VSC" => Some("ViewSonic"),
        "HSD" => Some("HannStar Display"),
        "BOE" => Some("BOE"),
        "CPT" => Some("Chunghwa Picture Tubes"),
        "AMR" => Some("AmTRAN"),
        "CHI" => Some("Chimei Innolux"),
        _ => None,
    }
}
